apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: elementary-application
  name: elementary-application
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elementary-application
    spec:
      containers:
      - image: demo-elementary-application:1
        name: elementary-application
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /data/demo-elementary-application
          name: elementary-application-claim0
      restartPolicy: Always
      volumes:
      - name: elementary-application-claim0
        persistentVolumeClaim:
          claimName: elementary-application-claim0
status: {}
