spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: potato
    password: potato123
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

server:
  port: 8082
